name: find_work_or_worker
description: This project for search work and worker
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  glassmorphism: ^3.0.0
  lottie: ^2.6.0
  device_preview: ^1.1.0
  image_picker: ^1.0.4
  shared_preferences: ^2.2.1
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  flutter_native_splash: ^2.3.3
  flutter_cache_manager: ^3.3.1
  gallery_saver: ^2.3.2
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  path: ^1.8.3
  http: ^0.13.6
  hive_flutter: ^1.1.0
  flutter_verification_code: ^1.1.7
  cupertino_icons: ^1.0.2
  jwt_decoder: ^2.0.1
  flutter_secure_storage: ^9.0.0
  equatable: ^2.0.5
  dio: ^5.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/lotties/
    - assets/image/